### ISSUE TITLE
auto close popup after seconds

### ISSUE THREAD

**Issue by yajuvendra1990** [daankuijsten/simple-popup#2]
I am using simple popup and I want to auto close popup after seconds. Please guide me how to do that

`jQuery(document).ready(function($) {
                $(".movenext").on("click", function(e) {
                    e.preventDefault();
                    $(this).simplePopup({
						type: "html",
						htmlSelector: "#popupuser"},
						setTimeout(function(){
              				$(this).simplePopup().close();
            			}, 3000)
					);										
                });
            });`

**Comment by dinoqqq** [comment]
@yajuvendra1990 , you can use the `afterOpen` callback function in the `options` object and pass it to the `simplePopup` function. Just put the timeout in there. In this example you can see how all callbacks are used:

```
 $(document).ready(function() {
                var options = {
                    beforeOpen: function(html) {
                        html.find(".simple-popup-content").prepend("<h1>Voila</h1>");
                    },
                    afterOpen: function(html) {
                        html.find(".simple-popup-content").css("background", "lightgreen");
                    },
                    beforeClose: function(html) {
                        alert("We are going to close now!");
                    },
                    afterClose: function() {
                        alert("Closed now!");
                    }
                };
                $("a.five").on("click", function(e) {
                    e.preventDefault();
                    $(this).simplePopup(options);
                });
            });
```
https://daankuijsten.github.io/simple-popup/
